name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.15
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  http: ^1.2.2
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/ss/
     - assets/
     - assets/svg/
     - assets/svg/figma.svg
     - assets/emoji/
